### ISSUE TITLE
Problem with setElementModel

### ISSUE THREAD

**Issue by httpRick** [Fernando-A-Rocha/mta-add-models#6]
Everyone has a server written differently and this can help, for example, someone changes their clothes in the setElementModel store, so why should I add a removeElementData to take a custom skin

**Comment by Fernando-A-Rocha** [comment]
So according to what you are saying, if I have a script that sets the player's skin to some ID using setElementModel serverside, you want that to do removeElementData shortly after.

The reason I disagree with this is because ALL skin IDs are to be set with setElementData(ped, "skinID", id) and not just custom ones. So removing that element data is not needed, this library handles setting default element models for you.

The solution I see to the problem of having to edit all your scripts to add this ismaybe usingve [addDebugHook](https://wiki.multitheftauto.com/wiki/AddDebugHook) to listen for:
- `setElementModel`
- `getElementModel`
- `createPed`
- `createVehicle`
- `createObject`
- `spawnPlayer`

🤔 @httpRick

**Comment by Fernando-A-Rocha** [comment]
In my personal project, to implement custom skin support across all resources, I mass replaced `getElementModel` to `exports.mylibrary:getElementModelNew` and `setElementModel` with `exports.mylibrary:setElementModelNew` to handle the setting/getting custom model ID element data.

**Comment by Fernando-A-Rocha** [comment]
After discussing with Rick on discord Ive acknowledged that:
- This library shouldn't handle setting default IDs, no reason.
- Keeping data for default IDs means more memory

So I decided to make changes to the library to allow using setElementModel and getElementModel serverside on other scripts, it'll be fine. You can use setElementModel to set a default ID, the script will now handle it properly.

Great suggestion and eye-opener, thank you @httpRick
