### ISSUE TITLE
[Feedback] Share your impressions and creations

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [Fernando-A-Rocha/mta-add-models#7]
Hi, I would really like to read your feedback if you've tested the resource(s) or even just read the documentation. Thank you! ❤️

**Comment by Fernando-A-Rocha** [comment]
> **hi i need some help with you script if you can help me i will be thanks.**

hey you can contact me on Discord Nando#7736 although I have limited time for support nowadays, I would appreciate if people worked on improving the main guide / documentation 🙏

**Comment by XPAN0509** [comment]
Hiya , I downloaded the script and combined it with exports fuctions in order to work with buycarsmod.
The folder named [order] with folders 'buycarsmod' and 'newmodels'
I wanted to upload new models meanwhile save the cars in 'buycarsmod' with their handlings

I was using 'buycarsmod' with commands : /acarcreate and /acarmodel 80001 ( they works)
and then I used 'hedit' to change handlings.
and then I restarted 'newmodels' , the reloading of replacement of TXDS and DFFS happens on clients side. (I THINK)
The cars created through 'buycarsmod' losd the handlings and changed back to the default ones of original models like Elegant.
My understanding is that the replacement happens on client side which will sit the handling back to orginals.

I was trying to fix it with several ways:
1. Change the order of restarting resouces.    --- not work because they happened on client sides.
2. Copy a new folder of [order]  named [order1] , and change functions in 'buycarsmod' and named 'buycarsmod1' . It works when one is started. When both of them started, the vehicle will change back to its original TXDS and DFFS because of StreamedOut functions
-- I tried to delete streamed functions but it doesnt work D: due to my poor skills.
4.  Exports IDs like '80001' in to a file change the cars with handling accordingly when people get in a car.

Is there any ways I can do with it ?

**Comment by Fernando-A-Rocha** [comment]
> Hiya , I downloaded the script and combined it with exports fuctions in order to work with buycarsmod.
> The folder named [order] with folders 'buycarsmod' and 'newmodels'
> I wanted to upload new models meanwhile save the cars in 'buycarsmod' with their handlings
> 
> I was using 'buycarsmod' with commands : /acarcreate and /acarmodel 80001 ( they works)
> and then I used 'hedit' to change handlings.
> and then I restarted 'newmodels' , the reloading of replacement of TXDS and DFFS happens on clients side. (I THINK)
> The cars created through 'buycarsmod' losd the handlings and changed back to the default ones of original models like Elegant.
> My understanding is that the replacement happens on client side which will sit the handling back to orginals.
> 
> I was trying to fix it with several ways:
> 1. Change the order of restarting resouces.    --- not work because they happened on client sides.
> 2. Copy a new folder of [order]  named [order1] , and change functions in 'buycarsmod' and named 'buycarsmod1' . It works when one is started. When both of them started, the vehicle will change back to its original TXDS and DFFS because of StreamedOut functions
> -- I tried to delete streamed functions but it doesnt work D: due to my poor skills.
> 4.  Exports IDs like '80001' in to a file change the cars with handling accordingly when people get in a car.
> 
> Is there any ways I can do with it ? 
>  

Solved your issue via Discord 👍🏼 leg me know if you have more questions

**Comment by IZSSlovakia** [comment]
Hi. Please I'm trying to contact you but I can't find you on Discord, are you still online there? We are trying to connect your script with owlgaming mod, adding skins and objects is working but adding vehicles is not, can you give me any advice?

**Comment by Fernando-A-Rocha** [comment]
> Hi. Please I'm trying to contact you but I can't find you on Discord, are you still online there? We are trying to connect your script with **owlgaming mod**, adding skins and objects is working but adding vehicles is not, can you give me any advice? **My Discord: Like Mike#6021**

Hi, sent you a friend request.

**Comment by IZSSlovakia** [comment]
> 

Hi, yes I'm online every day and I don't understand why I can't get in touch with you, if I may ask you to join our Discord (invitation https://discord.gg/QykMm3eP ) I'll look you up immediately and get in touch with you, then you can unsubscribe from our Discord. Thank you.

**Comment by IZSSlovakia** [comment]
I didn't get any request so I tried to send you a request anyway.
