### ISSUE TITLE
Weird behavior with object streaming out & then engineFreeModel

### ISSUE THREAD

**Issue by Fernando-A-Rocha** [Fernando-A-Rocha/mta-add-models#8]
Explained here: [testing script line 71](https://github.com/Fernando-A-Rocha/mta-add-models/blob/main/unittest_newmodels/server.lua#L71) (where it says NOT OK)

The added `unittest_newmodels` resource is for stress-testing everything and trying to find issues like this one :)
Special thanks to @httpRick for helping out

**Comment by Fernando-A-Rocha** [comment]
**How to reproduce bug:**

- add newmodels and unittest_newmodels resources 
- uncomment the "EXAMPLE OBJECT TEST" code from server.lua in the testing resource
- start it 
- you will be TPed to center of map automatically and observe the issue

**Comment by quiret** [comment]
I had the same issue when working on my own model streamer. I fixed it by detecting the recursion directly. You see, you can expect the streamer to stream-out the element in the way you detected it, all the time. That was the "fix" for me at scene2res.

**Comment by Fernando-A-Rocha** [comment]
> I had the same issue when working on my own model streamer. I fixed it by detecting the recursion directly. You see, you can expect the streamer to stream-out the element in the way you detected it, all the time. That was the "fix" for me at scene2res.

Interesting! But don't you believe we could get to the root of the problem in MTA code and prevent it from happening? Or is there a reason this happens?

**Comment by Fernando-A-Rocha** [comment]
Reopening issue because I think we need to discuss why this bug happens and if there an actual way to fix it within MTA code?

**Comment by quiret** [comment]
Technically the stream-out is related to the destruction of the real game entity. You can fix it by doing a manual model, texture and collision update on the entity. I am not sure about all the game variables that need adjustment, especially since there could be hooks all over the place and dependent MTA hacks, but it should be possible. But do you really want to mess with the buggy game logic any further and risk evoking more bugs in MTA?

**Comment by quiret** [comment]
- there is a bug related to vehicle collisions where the game updates the model data of the provided collision model but that model is reused in other places, causing vehicle wheels to got weird; can be fixed by an actual full-clone of the collision data of a collision model.
- vehicle wheels need to be recalculated on model switch which is happening if you recreate the vehicle (stream-in and stream-out) of course.
- objects are the easiest to update because they don't do collision modifications and have only atomics as rendered model data
- peds are not investigated by me; this could be a major hell-hole.

**Comment by Fernando-A-Rocha** [comment]
Thank you for making it clearer @quiret ! I guess this temp fix will be fine for now...
